# Generated by Django 5.0.6 on 2025-01-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('FIN', 'Finance'), ('MKT', 'Marketing'), ('SALES', 'Sales'), ('ENG', 'Engineering'), ('ADMIN', 'Administration')], max_length=50, verbose_name='department'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(blank=True, choices=[('Developer', 'Developer'), ('Designer', 'Designer'), ('Analyst', 'Analyst'), ('Tester', 'Tester'), ('Support', 'Support'), ('Manager', 'Manager'), ('Executive', 'Executive'), ('Senior Executive', 'Senior Executive'), ('Lead Developer', 'Lead Developer'), ('Junior Developer', 'Junior Developer'), ('Senior Developer', 'Senior Developer'), ('Intern', 'Intern')], max_length=50, verbose_name='job title'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employee', 'employee'), ('manager', 'manager'), ('admin', 'admin')], default='user', max_length=20),
        ),
    ]
